import nodePath from 'node:path'

import fse from 'fs-extra'
import {$} from 'execa'

import randomToken from '../utilities/random-token.js'
import {listAclsForPath, type FileAclRow} from './file-acls.js'
import {listUsers} from '../database/index.js'
import {listGroupMembers} from '../database/groups.js'

import type Livinityd from '../../index.js'
import type {FileChangeEvent} from './watcher.js'

// Global Samba config
const SMB_CONFIG = `# Generated by livinityd

[global]
# In standalone operation, a client must first "log-on" with a valid username
# and password stored on this machine.
server role = standalone

# The name of the Samba server that will show in clients.
server string = Livinity

# Defer to mDNS for discovery instead of advertising uppercase NETBIOS name.
mdns name = mdns

# Use Systemd for logging.
# Samba still tries to log to file, so pipe that to /dev/null.
logging = systemd
log file = /dev/null

# Make sure that we are not leaking information to guests or anonymous users.
access based share enum = yes
restrict anonymous = 2
map to guest = never

# Better compatibility for macOS clients
# https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X
vfs objects = catia fruit streams_xattr
fruit:metadata = stream
fruit:model = MacSamba
fruit:veto_appledouble = no
fruit:nfs_aces = no
fruit:wipe_intentionally_left_blank_rfork = yes
fruit:delete_empty_adfiles = yes
fruit:posix_rename = yes

# Disable printing services.
load printers = no
disable spoolss = yes
`

// The synthetic-account prefix — each LivOS login <username> maps to the
// login-less Unix + Samba account livos-<username> provisioned by the root
// wrapper (scripts/install/livos-samba-user.sh). MUST stay in lockstep with the
// wrapper's ACCOUNT_PREFIX so the render-time `valid users` list names the exact
// accounts smbpasswd knows about.
export function sambaAccountName(username: string): string {
	return `livos-${username}`
}

// LEGACY single-account share config (pre-migration, D-09). Kept VERBATIM in
// BEHAVIOR so existing LAN shares keep working until an admin opts into the
// per-user model (store `samba.perUserAuth`). Everything routes through the single
// shared "livinity" account with a blanket force-user-root mapping.
//
// NOTE (ordering, T-324): the blanket-root directive is placed ABOVE the
// shared-account allow-line here so it is unambiguously the LEGACY path — the
// per-user block below carries NO force-user-root line at all.
const legacyShareConfig = (name: string, path: string) => `
# Share specific config (LEGACY single-account model)
[${name}]
path = ${path}
writeable = yes

# Handle permissions (LEGACY)
# We force root so samba can read files that could be created by app processes
# running as various users including root.
# We inherit owner to avoid breaking permissions for apps that expect files in
# their data directories to be owned by them.
force user = root
force group = livinity
inherit owner = yes

# Enable Time Machine backups.
fruit:time machine = yes

# Only allow the shared "livinity" account to access the share.
valid users = livinity
`

// PER-USER share config (324-04 / FILES-02, D-09). `valid users` + `write list` are
// the LITERAL synthetic accounts (livos-<username>) resolved from the file_acls
// grants at smb.conf RENDER TIME — NO `net groupmap` / NSS group sync, the same
// resolve-at-render idiom applyShares already uses for virtualToSystemPath. A
// write-level grant places the account on `write list`; a read grant grants
// browse/read only. The blanket force-user-root mapping is DROPPED so on-disk
// access follows the per-user account's own uid.
//
// WHY A REAL UNIX ACCOUNT + AN NTLM SECONDARY PASSWORD (files/webdav.ts:13-34
// divergence): stock Samba has NO external_auth_hook (unlike SFTPGo/WebDAV) so it
// cannot delegate auth to livinityd's PG bcrypt table at login; NTLM also cannot be
// derived from a bcrypt hash. Per-user Samba therefore structurally requires a real
// (synthetic, login-less) Unix account + a generate-once SECONDARY password in the
// smbpasswd DB — never the login password. Provisioning is done by the root wrapper.
const perUserShareConfig = (name: string, path: string, validUsers: string[], writeList: string[]) => `
# Share specific config (PER-USER model — blanket force-user-root dropped)
[${name}]
path = ${path}

# The share is READ-ONLY by default and write access is ELEVATED per-account via
# \`write list\` (324-review WR-01). \`writeable = yes\` would make the WHOLE share
# read-write for every valid user and reduce \`write list\` to a no-op, so a
# read-level ACL grant would silently allow SMB writes — the canonical Samba pattern
# for per-user read/write separation is \`read only = yes\` + \`write list\`.
read only = yes

# valid users / write list = the literal synthetic accounts resolved from the
# file_acls grants at render time. A read-level grant lands ONLY on \`valid users\`
# (browse/read); a write-level grant ALSO lands on \`write list\` (read + write).
valid users = ${validUsers.join(' ')}
write list = ${writeList.join(' ')}

# On-disk access follows the per-user account's own uid (no blanket root mapping).
force group = livinity
inherit owner = yes

# Enable Time Machine backups.
fruit:time machine = yes
`

// Render a single share's smb.conf block. `perUser === null` → the LEGACY shared
// account block (blanket force-user-root); otherwise the per-user block driven by the
// render-time-resolved {validUsers, writeList}. Pure + exported for unit coverage.
export function renderShareBlock(
	name: string,
	path: string,
	perUser: {validUsers: string[]; writeList: string[]} | null,
): string {
	if (perUser === null) return legacyShareConfig(name, path)
	// 324-review WR-02 — FAIL CLOSED on a per-user share with NO applicable grants.
	// Samba treats an empty `valid users =` as its default (any authenticated account
	// may log in), so rendering an ungranted share would fall OPEN to every provisioned
	// livos-* account. Skip the block entirely instead — an ungranted per-user share is
	// simply not exported, so it is unreachable rather than open-to-all.
	if (perUser.validUsers.length === 0) return ''
	return perUserShareConfig(name, path, perUser.validUsers, perUser.writeList)
}

// Resolve a share's file_acls grants into the literal Samba account lists at render
// time. PURE (injectable resolvers) so the truth table is unit-testable OFFLINE (no
// live PG). For each non-`none` grant: a user-principal resolves to one username, a
// group-principal expands to every member's username; each is mapped to its
// livos-<username> synthetic account. `valid users` is the union of read+write
// accounts; `write list` is the subset with a write-level grant. Deduped.
export async function resolveSambaShareAcls(
	acls: readonly FileAclRow[],
	resolvers: {
		resolveUsername: (userId: string) => Promise<string | null>
		resolveGroupMembers: (groupId: string) => Promise<string[]>
	},
): Promise<{validUsers: string[]; writeList: string[]}> {
	const valid = new Set<string>()
	const write = new Set<string>()
	for (const grant of acls) {
		// A `none` grant is an explicit deny — it contributes NO valid-users entry.
		if (grant.level === 'none') continue
		let usernames: string[] = []
		if (grant.principal_type === 'user') {
			const username = await resolvers.resolveUsername(grant.principal_id)
			if (username) usernames = [username]
		} else {
			usernames = await resolvers.resolveGroupMembers(grant.principal_id)
		}
		for (const username of usernames) {
			const account = sambaAccountName(username)
			valid.add(account)
			if (grant.level === 'write') write.add(account)
		}
	}
	return {validUsers: [...valid], writeList: [...write]}
}

export default class Samba {
	#livinityd: Livinityd
	logger: Livinityd['logger']
	#removeFileChangeListener?: () => void

	constructor(livinityd: Livinityd) {
		this.#livinityd = livinityd
		const {name} = this.constructor
		this.logger = livinityd.logger.createChildLogger(`files:${name.toLocaleLowerCase()}`)
	}

	// Add listener
	async start() {
		this.logger.log('Starting samba')

		// Make sure the share password exists and is applied
		await this.applySharePassword().catch((error) => {
			this.logger.error(`Failed to apply share password`, error)
		})

		// Apply shares (and start Samba/wsdd2 if needed)
		await this.applyShares().catch((error) => {
			this.logger.error(`Failed to apply shares`, error)
		})

		// Attach listener
		this.#removeFileChangeListener = this.#livinityd.eventBus.on(
			'files:watcher:change',
			this.#handleFileChange.bind(this),
		)
	}

	// Remove listener
	async stop() {
		this.logger.log('Stopping samba')
		this.#removeFileChangeListener?.()
		await $`systemctl stop smbd`.catch((error) => this.logger.error(`Failed to stop samba`, error))
		await $`systemctl stop wsdd2`.catch((error) => this.logger.error(`Failed to stop wsdd2`, error))
	}

	// Gets the share password
	// On first run it will generate a random password and save it to the file.
	// TODO: Some kind of livinityd.secrets.get() api for dealing with this kind
	// of stuff might be nice in the future.
	async getSharePassword() {
		const sharePasswordFile = `${this.#livinityd.dataDirectory}/secrets/share-password`

		// Get or create the share password.
		// Phase 257-06 (LIVOS-039): write mode 0600 like the sibling secrets
		// (jwt, openclaw-ed25519) — the default umask-022 write was 0644, leaving
		// the share secret group/world-readable if the parent chain is ever loosened.
		const sharePassword = await fse.readFile(sharePasswordFile, 'utf8').catch(async () => {
			this.logger.log('Creating share password on first run')
			const sharePassword = randomToken(128)
			await fse.writeFile(sharePasswordFile, sharePassword, {mode: 0o600})
			return sharePassword
		})

		// LIVOS-039: correct an EXISTING 0644 file (the live Mini PC's current
		// state) to 0600 on next access. Best-effort — ignore platforms/FS that
		// don't support POSIX modes.
		await fse.chmod(sharePasswordFile, 0o600).catch(() => {})

		return sharePassword
	}

	// Applies the share password to the Samba user
	async applySharePassword() {
		const sharePassword = await this.getSharePassword()
		await $({
			input: `${sharePassword}\n${sharePassword}\n`,
		})`smbpasswd -s -a livinity`
	}

	// Whether the OPT-IN per-user Samba auth model is enabled (324-04, D-09). Default
	// false — existing single-account LAN shares keep working (blanket force-user-root)
	// until an admin explicitly opts into the BREAKING per-user cutover. Fail-soft: a
	// missing/undecodable store key reads as legacy-off.
	async isPerUserAuthEnabled() {
		const state = await this.#livinityd.store.get('samba').catch(() => undefined)
		return state?.perUserAuth ?? false
	}

	// Opt into (or back out of) the per-user auth model. This is a BREAKING migration
	// (existing SMB clients using the shared "livinity" account will need to
	// re-authenticate as their own livos-<username> account with the per-user
	// SECONDARY password) — the caller is responsible for surfacing that warning + a
	// release note. Flips the flag then re-renders smb.conf. Kept SEPARATE from the
	// wrapper-driven account provisioning (system/routes.ts runSambaUser).
	async setPerUserAuth(enabled: boolean) {
		const state = await this.#livinityd.store.get('samba').catch(() => undefined)
		await this.#livinityd.store.set('samba', {
			perUserAuth: enabled,
			provisionedUsers: state?.provisionedUsers ?? [],
		})
		await this.applyShares().catch((error) => this.logger.error('Failed to re-apply shares after migration toggle', error))
	}

	// Gets (or generates once) a PER-USER Samba SECONDARY password. Clones the single
	// getSharePassword() surface per-user: a 128-char random token written 0600 under
	// `secrets/samba-user-<username>-password`. It is NEVER synced from the login
	// password (NTLM cannot derive from bcrypt — the login plaintext is never held by
	// LivOS) and is surfaced to the user ONCE so they can enter it in their SMB client.
	async getUserSambaPassword(username: string) {
		const file = `${this.#livinityd.dataDirectory}/secrets/samba-user-${username}-password`
		const password = await fse.readFile(file, 'utf8').catch(async () => {
			this.logger.log(`Creating per-user Samba secondary password for ${username}`)
			const generated = randomToken(128)
			await fse.writeFile(file, generated, {mode: 0o600})
			return generated
		})
		await fse.chmod(file, 0o600).catch(() => {})
		return password
	}

	// Resolve a share's file_acls grants → the literal {validUsers, writeList} Samba
	// account lists at render time. Wires the pure resolveSambaShareAcls to the live
	// DB (listUsers for user-principals, listGroupMembers for group-principals). Fully
	// fail-soft: any DB error resolves to no extra accounts (the share renders with an
	// empty valid-users list rather than throwing mid-render).
	async #resolveShareAcls(virtualPath: string) {
		const acls = await listAclsForPath(virtualPath).catch(() => [] as FileAclRow[])
		return resolveSambaShareAcls(acls, {
			resolveUsername: async (userId) => {
				const users = await listUsers().catch(() => [])
				return users.find((u) => u.id === userId)?.username ?? null
			},
			resolveGroupMembers: async (groupId) => {
				const members = await listGroupMembers(groupId).catch(() => [])
				return members.map((m) => m.username)
			},
		})
	}

	// Apply shares to Samba
	async applyShares() {
		const shares = await this.#get()
		const perUserAuth = await this.isPerUserAuthEnabled()

		// Generate Samba config
		let config = SMB_CONFIG
		for (const share of shares) {
			// Make Livinity shares easily detectable in clients
			const shareName = await this.#computeSharename(share.name, share.path)

			// Resolve the render-time valid-users/write-list from file_acls BEFORE we
			// mutate share.path (the ACL DAO keys on the VIRTUAL path).
			const perUser = perUserAuth ? await this.#resolveShareAcls(share.path) : null

			// Convert to system path
			const systemPath = await this.#livinityd.files.virtualToSystemPath(share.path)

			// Append the share config (legacy shared-account block, or the per-user
			// block driven by the render-time-resolved grants).
			config += renderShareBlock(shareName, systemPath, perUser)
		}

		// Write out Samba config
		await fse.writeFile('/etc/samba/smb.conf', config)

		// If we don't have any shares, ensure samba isn't running and return
		if (shares.length === 0) return await $`systemctl stop smbd`

		// Otherwise start samba, or reload it's config if it's already running
		await $`systemctl start smbd`
		await $`smbcontrol smbd reload-config`

		// We also start wsdd2 for better Windows discovery.
		// We need to manually start this along with samba because if we boot with wsdd2
		// enabled but without samba it will shutdown when it sees samba isn't running.
		// It won't then auto start if a share is added later.
		await $`systemctl start wsdd2`
	}

	// Compute a client-facing sharename so that shares are easily detectable in clients
	async #computeSharename(name: string, path: string) {
		// Default to "name (Livinity)"
		let sharename = `${name} (Livinity)`
		if (path === '/Home') {
			// But Share /Home as "username's Livinity"
			const user = await this.#livinityd.user.get()
			const username = user?.name
			if (username) sharename = `${username}'s Livinity`
		}
		return sharename
	}

	// Read current shares from the store
	async #get() {
		const shares = await this.#livinityd.store.get('files.shares')
		return shares || []
	}

	// Remove shares on deletion
	// TODO: It would be nice if we could handle updating favorites when the favorited directory is
	// moved/renamed. It's not trivial because this can happen via something external like an app or SMB
	// and there's no way to tell the difference between a move/rename and a deletion/recreation.
	async #handleFileChange(event: FileChangeEvent) {
		if (event.type !== 'delete') return
		const shares = await this.#get()
		const virtualDeletedPath = this.#livinityd.files.systemToVirtualPath(event.path)
		const deletedShares = shares.filter((share) => share.path.startsWith(virtualDeletedPath))
		for (const share of deletedShares) await this.removeShare(share.path)
	}

	// List favorited directories
	async listShares() {
		// Get shares from the store
		const shares = await this.#get()

		// Strip out any shares that aren't existing directories
		const mappedShares = await Promise.all(
			shares.map(async (share) => {
				const systemPath = await this.#livinityd.files.virtualToSystemPath(share.path)
				const file = await this.#livinityd.files.status(systemPath).catch(() => undefined)
				if (file?.type !== 'directory') return undefined
				return share
			}),
		)
		const filteredShares = mappedShares.filter((share) => share !== undefined)

		// Compute client-facing sharenames using the same logic used when generating smb.conf.
		const sharesWithSharenames = await Promise.all(
			filteredShares.map(async (share) => ({
				...share,
				sharename: await this.#computeSharename(share.name, share.path),
			})),
		)
		return sharesWithSharenames
	}

	// Share a new directory
	async addShare(virtualPath: string) {
		// Check if operation is allowed
		const allowedOperations = await this.#livinityd.files.getAllowedOperations(virtualPath)
		if (!allowedOperations.includes('share')) throw new Error('[operation-not-allowed]')

		// Add share
		this.logger.log(`Adding share for ${virtualPath}`)

		// Aquire write lock on the store
		await this.#livinityd.store.getWriteLock(async ({set}) => {
			// Get current shares
			const shares = await this.#get()

			// Error if share already exists
			const shareExists = shares.some((share) => share.path === virtualPath)
			if (shareExists) throw new Error('[share-already-exists]')

			// Set unique share name
			let name = nodePath.basename(virtualPath)
			let i = 1
			while (shares.some((share) => share.name === name)) {
				i++
				if (i > 10) throw new Error('[share-name-generation-failed]')
				name = `${nodePath.basename(virtualPath)} (${i})`
			}

			// Add share to the store
			await set('files.shares', [...shares, {name, path: virtualPath}])
		})

		// Apply changes to Samba
		await this.applyShares()

		// Return virtual path
		return virtualPath
	}

	// Remove a share
	async removeShare(virtualPath: string) {
		this.logger.log(`Removing share for ${virtualPath}`)

		let deleted = false
		await this.#livinityd.store.getWriteLock(async ({set}) => {
			const shares = await this.#get()
			const newShares = shares.filter((share) => share.path !== virtualPath)
			deleted = newShares.length < shares.length
			if (deleted) await set('files.shares', newShares)
		})

		// Apply changes to Samba
		if (deleted) {
			// Note: Clients that are already connected to a removed share will continue to stay
			// connected. This is intentional behaviour by samba to avoid corruption by force disconnecting
			// users while they might be using a share.
			// We can force disconnect with `smbcontrol smbd close-share $share` but it could be dangerous
			// and it doesn't work reliably accross clients. macOS drops the connection immediately. Linux
			// shows the files but errors on any navigation or write. Windows continues to stay connected.
			await this.applyShares()
		}

		// Return deleted boolean
		return deleted
	}
}
