#!/usr/bin/env bash
# scripts/install/livos-waf.sh
# Phase 332 (WAF-01) — root-owned fail2ban abuse-jail wrapper for the app-layer WAF.
#
# Deployed to /usr/local/lib/livos/livos-waf.sh (mode 0755, root-owned) by
# deploy-livinityd.sh + update.sh (mirrors livos-pool.sh / livos-ups.sh). Invoked by
# livinityd's app-security path via the scoped sudoers grant (sudoers.d/livos-waf):
#   sudo -n /usr/local/lib/livos/livos-waf.sh <action> [args...]
#
# WHY A WRAPPER (clone of the livos-pool.sh / livos-os-patch.sh closed-enum idiom):
# livinityd runs as the unprivileged desktop user, but installing a fail2ban jail +
# creating the Caddy access-log dir + reloading fail2ban all need root. A raw NOPASSWD
# grant on fail2ban-client / tee / systemctl would let any process that can call `sudo`
# rewrite arbitrary jails or restart arbitrary services. Instead the sudoers grant is on
# THIS ONE binary path (no glob, no argument wildcard) and the wrapper accepts ONLY a
# fixed action enum. It builds every path/argv ITSELF; the ONLY caller-supplied inputs are
# three INTEGERS (maxretry / findtime / bantime), each re-validated against ^[0-9]{1,7}$
# INSIDE the script before it can reach a generated config. The jail + filter BODIES are
# fixed heredocs owned by this wrapper — no caller string is ever interpolated into them.
# To change a permitted operation, EDIT THIS WRAPPER — do NOT broaden the grant.
#
# THREAT MODEL: this is the WAF-01 rate-abuse leg. The jail bans a client IP that trips
# maxretry 4xx/5xx responses within findtime, for bantime seconds, over the DEDICATED Caddy
# access log dir (/var/log/livos-caddy) that only the 332 emit writes to. `ignoreip` defaults
# to loopback + RFC1918 so an operator on the LAN can NEVER be locked out of the dashboard by
# an app's ban list. iptables bans bite LAN-direct / portal traffic (real client TCP peer);
# tunnel-carried CF traffic terminates at localhost so the CF edge is the right layer there
# (Pro users already have SBFM/WAF) — documented, not a silent gap.
#
# NO LIVE EXECUTION ON THE DEV HOST: acceptance for this wrapper is `bash -n` + structural
# grep ONLY. install-jail / reload are exercised exclusively on a disposable test box in
# 332-HUMAN-UAT.md (operator-greenlit, TEST BOX FIRST).
#
# Actions (the enum is the ONLY control input; anything unmatched -> `*) exit 2`):
#   ensure-log-dir                         create /var/log/livos-caddy owned by the caddy user
#   install-jail --maxretry N --findtime N --bantime N   write the filter+jail, reload fail2ban
#   remove-jail                            remove the livos-caddy filter+jail, reload fail2ban
#   status                                 READ-ONLY `fail2ban-client status livos-caddy`
#   reload                                 reload fail2ban (re-read configs)
# Any action not in this list -> `*) exit 2` (default-reject) before any privileged command runs.
#
# Exit codes: 2 = bad usage / unknown action / invalid integer arg. Otherwise the underlying
#             command's status.

set -euo pipefail

# Must run as root (invoked via sudo by livinityd, or directly at install-test).
[[ "${EUID:-$(id -u)}" -eq 0 ]] || { echo "[livos-waf] must run as root" >&2; exit 2; }

# ── Wrapper-owned constants (no caller string ever reaches these) ─────────────
readonly LOG_DIR="/var/log/livos-caddy"
readonly FILTER_PATH="/etc/fail2ban/filter.d/livos-caddy.conf"
readonly JAIL_PATH="/etc/fail2ban/jail.d/livos-caddy.conf"
# The Caddy apt package runs the service as the `caddy` system user; the access log
# files must be writable by it. Fall back to root:root if the user is absent (dev/CI).
readonly LOG_OWNER="caddy"

# Bounded integer validation — the ONLY caller-supplied values that reach a config.
_valid_int() {
	[[ "$1" =~ ^[0-9]{1,7}$ ]] || { echo "[livos-waf] invalid integer: $1" >&2; exit 2; }
}

_ensure_log_dir() {
	mkdir -p "$LOG_DIR"
	if id -u "$LOG_OWNER" >/dev/null 2>&1; then
		chown "$LOG_OWNER:$LOG_OWNER" "$LOG_DIR"
	fi
	chmod 0755 "$LOG_DIR"
}

_write_filter() {
	# Filter keys the TRUE client IP. Caddy's JSON access log (332 emit) writes
	# request.client_ip, which is the real client because the global trusted_proxies +
	# client_ip_headers block resolves CF-Connecting-IP / X-Forwarded-For. The failregex
	# fires on 4xx/5xx responses (scanners / abuse), not on legitimate 2xx traffic.
	cat > "$FILTER_PATH" <<'FILTER'
# LivOS app-layer WAF abuse filter (Phase 332 WAF-01) — auto-generated by livos-waf.sh.
# Matches a client IP that received a 4xx/5xx response in Caddy's JSON access log.
[Definition]
failregex = "client_ip":"<HOST>"(?:,|.)*?"status":(?:4\d\d|5\d\d)
ignoreregex =
# Caddy logs `ts` as an epoch float (e.g. "ts":1730000000.123).
datepattern = "ts":{EPOCH}
FILTER
	chmod 0644 "$FILTER_PATH"
}

_write_jail() {
	local maxretry="$1" findtime="$2" bantime="$3"
	cat > "$JAIL_PATH" <<JAIL
# LivOS app-layer WAF abuse jail (Phase 332 WAF-01) — auto-generated by livos-waf.sh.
# Bans a client IP that trips maxretry 4xx/5xx responses within findtime, for bantime
# seconds, over the dedicated Caddy access-log dir. ignoreip keeps LAN/loopback safe so
# an operator can never be locked out of the dashboard by an app's abuse ban.
[livos-caddy]
enabled  = true
filter   = livos-caddy
logpath  = ${LOG_DIR}/*.log
maxretry = ${maxretry}
findtime = ${findtime}
bantime  = ${bantime}
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
backend  = auto
JAIL
	chmod 0644 "$JAIL_PATH"
}

_reload() {
	# Reload only if fail2ban is actually present/active; never hard-fail a caller that
	# just wanted the files written (the systemd reload happens on the box).
	if command -v fail2ban-client >/dev/null 2>&1; then
		fail2ban-client reload >/dev/null 2>&1 || systemctl reload fail2ban >/dev/null 2>&1 || true
	fi
}

action="${1:-}"
shift || true

case "$action" in
	ensure-log-dir)
		_ensure_log_dir
		;;
	install-jail)
		maxretry="" findtime="" bantime=""
		while [[ $# -gt 0 ]]; do
			case "$1" in
				--maxretry) maxretry="${2:-}"; shift 2 ;;
				--findtime) findtime="${2:-}"; shift 2 ;;
				--bantime)  bantime="${2:-}";  shift 2 ;;
				*) echo "[livos-waf] unknown arg: $1" >&2; exit 2 ;;
			esac
		done
		# Defaults when an integer was omitted (still validated).
		maxretry="${maxretry:-20}"
		findtime="${findtime:-60}"
		bantime="${bantime:-3600}"
		_valid_int "$maxretry"
		_valid_int "$findtime"
		_valid_int "$bantime"
		_ensure_log_dir
		_write_filter
		_write_jail "$maxretry" "$findtime" "$bantime"
		_reload
		;;
	remove-jail)
		rm -f "$JAIL_PATH" "$FILTER_PATH"
		_reload
		;;
	status)
		if command -v fail2ban-client >/dev/null 2>&1; then
			fail2ban-client status livos-caddy
		else
			echo "[livos-waf] fail2ban-client not installed" >&2
			exit 2
		fi
		;;
	reload)
		_reload
		;;
	*)
		echo "[livos-waf] unknown action: ${action:-<none>}" >&2
		exit 2
		;;
esac
