# scripts/install/mode-local-lan.sh
# Phase 104 plan 104-03 — real body (was stub in plan 104-02).
# Source: 104-RESEARCH.md §Example 1 (lines 634-718).
# Implements D-104-CADDY-PKI-IMPORT (pki block in its own file, imported by livinityd).
#
# Sourced by scripts/install.sh after parse_cli + detect_platform + detect_host_ip,
# so HOST_IP is already populated. Honors LIVINITY_LOCAL_TLD env override.

_install_dnsmasq_local_lan() {
    step "Installing dnsmasq for local-lan mode"

    # 1. Free port 53 from systemd-resolved (idempotent — Pitfall 2)
    mkdir -p /etc/systemd/resolved.conf.d
    local stub_drop="/etc/systemd/resolved.conf.d/no-stub.conf"
    if ! grep -qF "DNSStubListener=no" "$stub_drop" 2>/dev/null; then
        cat > "$stub_drop" <<'EOF'
[Resolve]
DNSStubListener=no
EOF
        systemctl restart systemd-resolved
        ok "systemd-resolved stub listener disabled"
    else
        ok "systemd-resolved already configured for dnsmasq"
    fi

    # 2. Install dnsmasq (idempotent — apt-get -y is no-op when already installed)
    apt-get install -y -qq dnsmasq

    # 3. Write /etc/dnsmasq.d/livinity.conf atomically (temp + mv)
    local user_tld="${LIVINITY_LOCAL_TLD:-livinity.local}"
    local conf="/etc/dnsmasq.d/livinity.conf"
    local tmp="${conf}.new"
    cat > "$tmp" <<EOF
# Generated by LivOS install.sh --mode local-lan (Phase 104 plan 104-03)
# Edit /etc/dnsmasq.d/livinity-override.conf for local overrides.
address=/.${user_tld}/${HOST_IP}
local=/${user_tld}/
no-resolv
server=1.1.1.1
server=1.0.0.1
bind-dynamic
stop-dns-rebind
EOF
    mv -f "$tmp" "$conf"

    systemctl enable --now dnsmasq
    systemctl restart dnsmasq
    ok "dnsmasq serving *.${user_tld} -> ${HOST_IP}"
}

_install_caddy_local_pki() {
    step "Provisioning Caddy internal PKI (pki-global.conf)"

    # Write stable pki-global.conf (livinityd's generateLocalCaddyfile imports this).
    # D-104-CADDY-PKI-IMPORT: pki block lives in its own file, NEVER inlined.
    mkdir -p /etc/caddy
    local pki_conf="/etc/caddy/pki-global.conf"
    if ! grep -qF "ca liv-local" "$pki_conf" 2>/dev/null; then
        cat > "$pki_conf" <<'EOF'
# Generated by LivOS install.sh --mode local-lan (Phase 104 plan 104-03)
# livinityd's generated Caddyfile imports this at the top.
# DO NOT EDIT — regenerated on install.sh re-run.
{
    pki {
        ca liv-local {
            name "LivOS Local CA"
            root_cn "LivOS Local Root"
        }
    }
}
EOF
        ok "Caddy /etc/caddy/pki-global.conf written"
    else
        ok "Caddy /etc/caddy/pki-global.conf already exists (idempotent)"
    fi

    # File permissions: caddy:caddy 0644 (the contents are public CA metadata)
    chown caddy:caddy "$pki_conf" 2>/dev/null || true
    chmod 0644 "$pki_conf"

    # NOTE: We do NOT reload Caddy here. Caddyfile body is generated by livinityd's
    # generateLocalCaddyfile() on first user activate. Reloading an empty/old
    # Caddyfile would fail or revert state.
}

# Public entry point (called by scripts/install.sh case dispatch)
install_mode_local_lan() {
    _install_dnsmasq_local_lan
    _install_caddy_local_pki
    # Mode markers + tld + host IP are written by install.sh itself + the
    # plan 104-02 stub already had these for idempotency-test stability.
    # Re-write defensively here so post-103 calls don't lose state.
    set_livos_redis_key "livos:domain:local_mode" "local-lan"
    set_livos_redis_key "livos:domain:local_tld" "${LIVINITY_LOCAL_TLD:-livinity.local}"
    set_livos_redis_key "livos:domain:host_ip" "$HOST_IP"
}
