# scripts/install/mode-cloud.sh
# Phase 104 plan 104-06 — real body (was stub in plan 104-02).
# Refactored from livos/install.sh's existing cloud-mode flow.
#
# CRITICAL: D-104-NO-PROD-IMPACT. Any behavior change MUST also update the
# byte-equivalence baseline fixtures captured from Mini PC SHA dab261cc, OR
# the regression test (docker/cloud-regression/scripts/test-cloud-byte-
# equivalence.sh) fails. Treat this file as a SUBSET of livos/install.sh's
# cloud-mode flow — never a superset.
#
# Source mapping (every action below traces back to livos/install.sh):
#   _install_cloudflared_for_cloud  ← livos/install.sh:502-513 install_cloudflared
#   _configure_caddy_for_cloud      ← livos/install.sh:487-499 install_caddy
#                                     + livos/install.sh:1271-1295 configure_caddy
#   _persist_cloud_mode_redis       ← new (Phase 104 marker — Redis key that
#                                     livinityd's domain module reads on boot
#                                     to know which TLS path to take; mirrors
#                                     local-lan + hybrid stubs in 104-02)

_install_cloudflared_for_cloud() {
    step "Installing cloudflared (cloud-mode tunnel client; carry-from livos/install.sh:502-513)"
    if command -v cloudflared &>/dev/null; then
        ok "cloudflared already installed: $(cloudflared --version 2>/dev/null | head -1)"
        return 0
    fi
    # NOTE: livos/install.sh:509 uses the .deb direct download
    # (https://github.com/cloudflare/cloudflared/releases/latest/...). For the
    # regression test we mirror that path verbatim so the resulting binary +
    # version match the Mini PC baseline. The pkg.cloudflare.com apt-repo path
    # is an equivalent alternative but introduces a NEW source.list file that
    # would surface as drift in the byte-equivalence diff.
    info "Installing cloudflared (direct .deb from GitHub releases)"
    curl -sSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb \
        -o /tmp/cloudflared.deb
    dpkg -i /tmp/cloudflared.deb
    rm -f /tmp/cloudflared.deb
    ok "cloudflared $(cloudflared --version 2>&1 | head -1) installed"
}

_configure_caddy_for_cloud() {
    step "Configuring Caddy (cloud mode — bootstrap Caddyfile)"

    # CRITICAL: cloud mode emits the SAME minimal Caddyfile shape as
    # livos/install.sh:1271-1295 configure_caddy(). It is NOT the full
    # multi-tenant generateFullCaddyfile() output — that one is regenerated by
    # livinityd's domain module on first domain.activate mutation (after rsync
    # deploy via update.sh writes /opt/livos/.env and starts livinityd).
    #
    # Cloud-mode-specific NEGATIVE invariants (enforced by
    # docker/cloud-regression/entrypoint.sh negative checks):
    #   - NO `pki { ca liv-local { ... } }` block (local-lan only)
    #   - NO `import /etc/caddy/pki-global.conf` (local-lan only)
    #   - NO `tls internal` directive (local-lan only)
    #   - NO `dns cloudflare {env...}` in Caddyfile (cloud mode does HTTP-01
    #     on Cloudflare proxy mode at the apex, NOT DNS-01 in Caddyfile)
    local domain="${CONFIG_DOMAIN:-localhost}"
    local use_https="${CONFIG_USE_HTTPS:-false}"

    mkdir -p /etc/caddy
    # Phase 201-06 → Phase 203-03 (D-203-05) → Phase 203-09 — Liv AI surface
    # routing is SPLIT:
    #   /liv-ai-app/openclawos[/*]  → :18789 (openclaw claw-gateway, strip_prefix via handle_path)
    #   /liv-ai-app/*                → :3010 (Next.js Phase 202 dashboard subapp)
    # Both handles placed ABOVE the catch-all so Caddy's matcher-specificity
    # rules steer Liv AI traffic away from the livinityd app gateway. Runtime
    # generator in livos/packages/livinityd/.../domain/caddy.ts emits the same
    # split for per-user vhosts; this bootstrap keeps :80 consistent before
    # livinityd regenerates the Caddyfile on first domain.activate.
    if [[ "$use_https" == "true" ]] && [[ "$domain" != "localhost" ]]; then
        cat > /etc/caddy/Caddyfile <<CADDYFILE
${domain} {
    handle_path /liv-ai-app/openclawos /liv-ai-app/openclawos/* {
        rewrite * /plugins/openclawos{path}
        reverse_proxy 127.0.0.1:18789
    }
    @livaiSubapp path /liv-ai-app /liv-ai-app/*
    handle @livaiSubapp {
        reverse_proxy 127.0.0.1:3010
    }
    handle {
        reverse_proxy 127.0.0.1:8080
    }
}
CADDYFILE
        ok "Caddy configured: ${domain} (auto-TLS via livinityd domain module; /liv-ai-app/openclawos → :18789; /liv-ai-app/* → :3010)"
    else
        cat > /etc/caddy/Caddyfile <<'CADDYFILE'
:80 {
    handle_path /liv-ai-app/openclawos /liv-ai-app/openclawos/* {
        rewrite * /plugins/openclawos{path}
        reverse_proxy 127.0.0.1:18789
    }
    @livaiSubapp path /liv-ai-app /liv-ai-app/*
    handle @livaiSubapp {
        reverse_proxy 127.0.0.1:3010
    }
    handle {
        reverse_proxy 127.0.0.1:8080
    }
}
CADDYFILE
        ok "Caddy configured: :80 -> localhost:8080 (HTTP only; cloud-mode bootstrap; /liv-ai-app/openclawos → :18789; /liv-ai-app/* → :3010)"
    fi

    # Enable + restart (idempotent; matches livos/install.sh:1293-1294).
    systemctl enable caddy 2>/dev/null || true
    systemctl restart caddy 2>/dev/null || true

    # Validate the Caddyfile (cheap; catches syntax errors before any cert
    # issuance attempt). Per RESEARCH §A5: this is the regression test's
    # cert-validity proxy — we cannot run live ACME inside a container, so
    # `caddy validate` stands in for "the config is correct shape".
    if command -v caddy &>/dev/null; then
        if ! caddy validate --config /etc/caddy/Caddyfile 2>/dev/null; then
            warn "caddy validate failed; review /etc/caddy/Caddyfile"
        else
            ok "Caddy config syntactically valid"
        fi
    fi
}

_persist_cloud_mode_redis() {
    # Cloud mode persists ONLY the host IP (the apex domain lives in /opt/livos/.env
    # which is written by update.sh on the Mini PC, NOT by install.sh). The mode
    # marker `livos:domain:local_mode=cloud` is written by install.sh's tail
    # after all mode bodies return — we do not double-write it here.
    set_livos_redis_key "livos:domain:host_ip" "${HOST_IP:-unknown}"
}

# Public entry point — called by scripts/install.sh dispatcher.
install_mode_cloud() {
    _install_cloudflared_for_cloud
    _configure_caddy_for_cloud
    _persist_cloud_mode_redis
    info "Cloud mode setup done. NOTE: full Mini PC parity requires update.sh + rsync deploy."
    info "install.sh --mode cloud handles system prereqs only; livinityd's domain"
    info "module finishes the cert + domain wiring via the existing Settings -> Domain UI."
}
