import { writeFileSync, existsSync, copyFileSync, chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

// ── Configuration interface ───────────────────────────────────────

export interface EnvConfig {
  // Domain
  domain: string;
  useHttps: boolean;

  // Secrets (auto-generated)
  jwtSecret: string;
  apiKey: string;
  redisPassword: string;

  // Channels
  telegramBotToken?: string;
  telegramDmPolicy?: 'open' | 'pairing';
  discordBotToken?: string;
  discordApplicationId?: string;

  // Voice (optional)
  deepgramApiKey?: string;
  cartesiaApiKey?: string;

  // Gmail (optional)
  gmailClientId?: string;
  gmailClientSecret?: string;

  // Paths
  livosBaseDir: string;
  nexusBaseDir: string;

  // Ports
  apiPort: number;
  mcpPort: number;
  memoryPort: number;
}

// ── Env file writer ───────────────────────────────────────────────

function buildProtocol(useHttps: boolean): string {
  return useHttps ? 'https' : 'http';
}

export function writeEnvFile(filePath: string, config: EnvConfig): void {
  const proto = buildProtocol(config.useHttps);
  const timestamp = new Date().toISOString();

  const lines: string[] = [
    '# ==============================================================================',
    '# LIVINITY ENVIRONMENT CONFIGURATION',
    '# ==============================================================================',
    `# Generated by: livinity onboard`,
    `# Date: ${timestamp}`,
    '#',
    '# NEVER commit this file with real values!',
    '# ==============================================================================',
    '',

    // ── AI Configuration ──
    '# === AI Configuration ===',
    '# v2.0 uses Claude Code Auth (subscription mode).',
    '# No API keys needed — AI runs via Claude Code SDK subscription.',
    '',

    // ── Security ──
    '# === Security ===',
    '# JWT signing secret (auto-generated, 32 bytes)',
    `JWT_SECRET=${config.jwtSecret}`,
    '',
    '# Internal API authentication key (auto-generated, 32 bytes)',
    `LIV_API_KEY=${config.apiKey}`,
    '',

    // ── Database ──
    '# === Database ===',
    '# Redis connection (password auto-generated)',
    `REDIS_URL=redis://:${config.redisPassword}@localhost:6379`,
    '',
    '# PostgreSQL for persistent storage (configure when needed)',
    'DATABASE_URL=',
    '',

    // ── Domain ──
    '# === Domain ===',
    `LIVOS_DOMAIN=${config.domain}`,
    `LIVOS_USE_HTTPS=${config.useHttps}`,
    '',

    // ── Server Ports ──
    '# === Server Ports ===',
    `MCP_PORT=${config.mcpPort}`,
    `API_PORT=${config.apiPort}`,
    `MEMORY_PORT=${config.memoryPort}`,
    '',

    // ── Service URLs ──
    '# === Service URLs ===',
    `NEXUS_API_URL=${proto}://localhost:${config.apiPort}`,
    `MEMORY_SERVICE_URL=${proto}://localhost:${config.memoryPort}`,
    '',

    // ── Paths ──
    '# === Paths ===',
    `LIVOS_BASE_DIR=${config.livosBaseDir}`,
    `NEXUS_BASE_DIR=${config.nexusBaseDir}`,
    '',
  ];

  // ── Channels ──
  lines.push('# === Channels ===');
  if (config.telegramBotToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${config.telegramBotToken}`);
    lines.push(`TELEGRAM_DM_POLICY=${config.telegramDmPolicy ?? 'pairing'}`);
  } else {
    lines.push('# TELEGRAM_BOT_TOKEN=');
    lines.push('# TELEGRAM_DM_POLICY=pairing');
  }
  lines.push('');

  if (config.discordBotToken) {
    lines.push(`DISCORD_BOT_TOKEN=${config.discordBotToken}`);
    lines.push(`DISCORD_APPLICATION_ID=${config.discordApplicationId ?? ''}`);
  } else {
    lines.push('# DISCORD_BOT_TOKEN=');
    lines.push('# DISCORD_APPLICATION_ID=');
  }
  lines.push('');

  // ── Voice (optional) ──
  if (config.deepgramApiKey || config.cartesiaApiKey) {
    lines.push('# === Voice ===');
    lines.push(`DEEPGRAM_API_KEY=${config.deepgramApiKey ?? ''}`);
    lines.push(`CARTESIA_API_KEY=${config.cartesiaApiKey ?? ''}`);
    lines.push('');
  }

  // ── Gmail (optional) ──
  if (config.gmailClientId || config.gmailClientSecret) {
    lines.push('# === Gmail Integration ===');
    lines.push(`GMAIL_CLIENT_ID=${config.gmailClientId ?? ''}`);
    lines.push(`GMAIL_CLIENT_SECRET=${config.gmailClientSecret ?? ''}`);
    lines.push('');
  }

  // ── Environment ──
  lines.push('# === Environment ===');
  lines.push('NODE_ENV=production');
  lines.push('');

  const content = lines.join('\n');

  // Ensure parent directory exists
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  // Write with restricted permissions (0o600 = owner read/write only)
  writeFileSync(filePath, content, { encoding: 'utf-8', mode: 0o600 });

  // Ensure permissions on platforms that ignore the mode flag
  try {
    chmodSync(filePath, 0o600);
  } catch {
    // Non-fatal — Windows doesn't support Unix permissions
  }
}

// ── Backup helper ─────────────────────────────────────────────────

/**
 * If an .env file already exists at `filePath`, create a timestamped backup.
 * @returns The backup path, or null if no file existed.
 */
export function backupEnvFile(filePath: string): string | null {
  if (!existsSync(filePath)) return null;

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupPath = `${filePath}.backup.${timestamp}`;

  copyFileSync(filePath, backupPath);
  return backupPath;
}
