/**
 * Livinity Marketplace Catalog
 * Curated capabilities from claude-code-templates, GSD, system prompts, community
 */

export interface MarketplaceItem {
  id: string
  type: 'skill' | 'agent' | 'mcp' | 'hook' | 'prompt'
  name: string
  description: string
  author: string
  version: string
  category: string
  tags: string[]
  triggers: string[]
  provides_tools: string[]
  requires: string[]
  conflicts: string[]
  context_cost: number
  tier: string
  install_source: 'npm' | 'github' | 'builtin'
  install_command?: string
  config?: Record<string, any>
}

const mcpServers: MarketplaceItem[] = [
  { id: 'mcp:filesystem', type: 'mcp', name: 'Filesystem', description: 'Read, write, and manage files on the server', author: 'Anthropic', version: '2025.1.0', category: 'Development', tags: ['files', 'filesystem', 'read', 'write', 'directory'], triggers: ['read file', 'write file', 'list directory'], provides_tools: ['read_file', 'write_file', 'list_directory', 'search_files', 'get_file_info'], requires: [], conflicts: [], context_cost: 500, tier: 'any', install_source: 'npm', install_command: 'npx -y @modelcontextprotocol/server-filesystem /opt/livos/data', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '/opt/livos/data'] } },
  { id: 'mcp:brave-search', type: 'mcp', name: 'Brave Search', description: 'Web and local search using Brave Search API', author: 'Anthropic', version: '2025.1.0', category: 'Research', tags: ['search', 'web', 'research', 'brave'], triggers: ['search', 'find online', 'web search', 'look up'], provides_tools: ['brave_web_search', 'brave_local_search'], requires: [], conflicts: [], context_cost: 300, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-brave-search'], env: { BRAVE_API_KEY: '' } } },
  { id: 'mcp:github', type: 'mcp', name: 'GitHub', description: 'Manage GitHub repos — issues, PRs, code search, branches', author: 'Anthropic', version: '2025.1.0', category: 'Development', tags: ['github', 'git', 'repository', 'code', 'issues'], triggers: ['github', 'create issue', 'pull request', 'search code'], provides_tools: ['create_or_update_file', 'search_repositories', 'create_issue', 'create_pull_request', 'get_file_contents'], requires: [], conflicts: [], context_cost: 600, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' } } },
  { id: 'mcp:puppeteer', type: 'mcp', name: 'Puppeteer Browser', description: 'Headless Chrome — navigate, click, fill forms, screenshots', author: 'Anthropic', version: '2025.1.0', category: 'Automation', tags: ['browser', 'puppeteer', 'scraping', 'automation', 'screenshot'], triggers: ['open website', 'browse', 'screenshot', 'scrape'], provides_tools: ['puppeteer_navigate', 'puppeteer_screenshot', 'puppeteer_click', 'puppeteer_fill'], requires: [], conflicts: [], context_cost: 400, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] } },
  { id: 'mcp:postgres', type: 'mcp', name: 'PostgreSQL', description: 'Query and manage PostgreSQL databases', author: 'Anthropic', version: '2025.1.0', category: 'Database', tags: ['database', 'postgres', 'sql', 'query'], triggers: ['database', 'sql', 'query', 'postgres'], provides_tools: ['query', 'list_tables', 'describe_table'], requires: [], conflicts: [], context_cost: 300, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost/mydb'] } },
  { id: 'mcp:memory', type: 'mcp', name: 'Memory / Knowledge Graph', description: 'Persistent memory with knowledge graph — entities, relations, observations', author: 'Anthropic', version: '2025.1.0', category: 'AI', tags: ['memory', 'knowledge', 'graph', 'remember', 'recall'], triggers: ['remember', 'recall', 'store', 'knowledge'], provides_tools: ['create_entities', 'create_relations', 'add_observations', 'search_nodes'], requires: [], conflicts: [], context_cost: 450, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'] } },
  { id: 'mcp:fetch', type: 'mcp', name: 'Web Fetch', description: 'Fetch URLs and convert to markdown for AI consumption', author: 'Anthropic', version: '2025.1.0', category: 'Research', tags: ['fetch', 'http', 'api', 'url', 'web', 'markdown'], triggers: ['fetch', 'get url', 'download', 'http'], provides_tools: ['fetch'], requires: [], conflicts: [], context_cost: 200, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-fetch'] } },
  { id: 'mcp:slack', type: 'mcp', name: 'Slack', description: 'Send messages, list channels, search in Slack workspaces', author: 'Anthropic', version: '2025.1.0', category: 'Communication', tags: ['slack', 'messaging', 'chat', 'channels'], triggers: ['slack', 'send message', 'channel'], provides_tools: ['send_message', 'list_channels', 'get_channel_history'], requires: [], conflicts: [], context_cost: 350, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-slack'], env: { SLACK_BOT_TOKEN: '', SLACK_TEAM_ID: '' } } },
  { id: 'mcp:sequential-thinking', type: 'mcp', name: 'Sequential Thinking', description: 'Step-by-step problem solving with branching and revision', author: 'Anthropic', version: '2025.1.0', category: 'AI', tags: ['thinking', 'reasoning', 'problem-solving', 'analysis'], triggers: ['think step by step', 'analyze', 'reason'], provides_tools: ['sequentialthinking'], requires: [], conflicts: [], context_cost: 200, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] } },
  { id: 'mcp:exa', type: 'mcp', name: 'Exa Search', description: 'AI-native semantic search — find similar pages, get contents', author: 'Exa', version: '1.0.0', category: 'Research', tags: ['search', 'semantic', 'research', 'exa'], triggers: ['search', 'find similar', 'semantic search'], provides_tools: ['exa_search', 'exa_find_similar', 'exa_get_contents'], requires: [], conflicts: [], context_cost: 300, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', 'exa-mcp-server'], env: { EXA_API_KEY: '' } } },
  { id: 'mcp:firecrawl', type: 'mcp', name: 'Firecrawl', description: 'Crawl websites and extract structured content', author: 'Firecrawl', version: '1.0.0', category: 'Research', tags: ['crawl', 'scrape', 'extract', 'sitemap', 'web'], triggers: ['crawl', 'scrape website', 'extract content'], provides_tools: ['firecrawl_scrape', 'firecrawl_map', 'firecrawl_crawl'], requires: [], conflicts: [], context_cost: 350, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', 'firecrawl-mcp'], env: { FIRECRAWL_API_KEY: '' } } },
  { id: 'mcp:context7', type: 'mcp', name: 'Context7', description: 'Up-to-date docs and code examples for any library', author: 'Context7', version: '1.0.0', category: 'Development', tags: ['docs', 'documentation', 'library', 'api', 'examples'], triggers: ['documentation', 'how to use', 'library docs'], provides_tools: ['resolve-library-id', 'get-library-docs'], requires: [], conflicts: [], context_cost: 250, tier: 'any', install_source: 'npm', config: { transport: 'stdio', command: 'npx', args: ['-y', '@upstash/context7-mcp'] } },
]

const agents: MarketplaceItem[] = [
  { id: 'agent:code-reviewer', type: 'agent', name: 'Code Reviewer', description: 'Expert code review — quality, security, maintainability with actionable feedback', author: 'Livinity', version: '1.0.0', category: 'Development', tags: ['review', 'code', 'quality', 'security'], triggers: ['review code', 'code review', 'check quality'], provides_tools: [], requires: [], conflicts: [], context_cost: 100, tier: 'sonnet', install_source: 'builtin', config: { systemPrompt: 'You are an expert code reviewer. Analyze for bugs, security (OWASP), performance, style, and error handling. Provide specific actionable feedback.', tools: ['shell', 'files_read', 'files_list'] } },
  { id: 'agent:devops-engineer', type: 'agent', name: 'DevOps Engineer', description: 'CI/CD, Docker, deployment automation and infrastructure management', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['devops', 'docker', 'deploy', 'ci-cd'], triggers: ['deploy', 'docker', 'ci/cd', 'infrastructure'], provides_tools: [], requires: [], conflicts: [], context_cost: 100, tier: 'sonnet', install_source: 'builtin', config: { systemPrompt: 'You are a DevOps specialist. Docker, CI/CD, infra automation, monitoring, deployment. Prefer automation. Verify before applying.', tools: ['shell', 'files_read', 'files_write', 'docker', 'docker_manage', 'pm2'] } },
  { id: 'agent:research-analyst', type: 'agent', name: 'Research Analyst', description: 'Deep web research — investigates topics, compares options, writes reports', author: 'Livinity', version: '1.0.0', category: 'Research', tags: ['research', 'analysis', 'report', 'compare'], triggers: ['research', 'investigate', 'analyze', 'compare'], provides_tools: [], requires: [], conflicts: [], context_cost: 100, tier: 'opus', install_source: 'builtin', config: { systemPrompt: 'You are a research analyst. Thorough research, multiple perspectives, well-structured reports with citations.', tools: ['shell', 'research', 'scrape', 'files_write'] } },
  { id: 'agent:server-monitor', type: 'agent', name: 'Server Monitor', description: 'Continuous health monitoring — CPU, RAM, disk, Docker, services on schedule', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['monitor', 'health', 'server', 'alerting'], triggers: ['monitor server', 'health check', 'server status'], provides_tools: [], requires: [], conflicts: [], context_cost: 80, tier: 'flash', install_source: 'builtin', config: { systemPrompt: 'Server monitoring agent. Check CPU, RAM, disk, Docker, PM2. Report anomalies. Keep reports concise.', tools: ['shell', 'sysinfo', 'docker', 'pm2'], loop: { intervalMs: 300000, task: 'Full server health check. Report issues.' } } },
  { id: 'agent:content-creator', type: 'agent', name: 'Content Creator', description: 'Blog posts, articles, social media — researches and writes engaging copy', author: 'Livinity', version: '1.0.0', category: 'Content', tags: ['content', 'writing', 'blog', 'article', 'social-media'], triggers: ['write article', 'blog post', 'content', 'copywriting'], provides_tools: [], requires: [], conflicts: [], context_cost: 100, tier: 'sonnet', install_source: 'builtin', config: { systemPrompt: 'Skilled content creator. Engaging prose, adapted to audience. Headings, bullets, CTAs. Research before writing.', tools: ['shell', 'research', 'files_write'] } },
  { id: 'agent:security-scanner', type: 'agent', name: 'Security Scanner', description: 'Vulnerability scanning — ports, SSL, headers, outdated packages', author: 'Livinity', version: '1.0.0', category: 'Security', tags: ['security', 'scan', 'vulnerability', 'audit'], triggers: ['security scan', 'vulnerability check', 'audit security'], provides_tools: [], requires: [], conflicts: [], context_cost: 100, tier: 'sonnet', install_source: 'builtin', config: { systemPrompt: 'Security scanner. Check ports, SSL, headers, packages, Docker, firewall. Prioritize by severity.', tools: ['shell', 'sysinfo'] } },
  { id: 'agent:backup-manager', type: 'agent', name: 'Backup Manager', description: 'Automated backups — schedule, verify integrity, manage retention', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['backup', 'restore', 'snapshot', 'retention'], triggers: ['backup', 'restore', 'snapshot'], provides_tools: [], requires: [], conflicts: [], context_cost: 80, tier: 'flash', install_source: 'builtin', config: { systemPrompt: 'Backup management. Create, verify, manage backups for DBs, files, Docker. Retention policies. Verify integrity.', tools: ['shell', 'files_read', 'files_write', 'docker'], loop: { intervalMs: 86400000, task: 'Daily backup verification.' } } },
]

const skills: MarketplaceItem[] = [
  { id: 'skill:server-health', type: 'skill', name: 'Server Health Check', description: 'Comprehensive health check — CPU, RAM, disk, Docker, PM2', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['health', 'server', 'monitoring'], triggers: ['health check', 'server health'], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'flash', install_source: 'builtin' },
  { id: 'skill:site-audit', type: 'skill', name: 'Website Audit', description: 'SEO, performance, security headers, SSL, accessibility audit', author: 'Livinity', version: '1.0.0', category: 'Research', tags: ['seo', 'audit', 'website', 'performance'], triggers: ['site audit', 'seo audit'], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'sonnet', install_source: 'builtin' },
  { id: 'skill:deploy', type: 'skill', name: 'Auto Deploy', description: 'Autonomous deployment — plan, execute, verify with rollback', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['deploy', 'install', 'setup'], triggers: ['deploy', 'install', 'setup'], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'sonnet', install_source: 'builtin' },
  { id: 'skill:lead-generation', type: 'skill', name: 'Lead Generation', description: 'Find companies, extract contacts, validate and deduplicate', author: 'Livinity', version: '1.0.0', category: 'Business', tags: ['leads', 'prospects', 'sales'], triggers: ['lead generation', 'find leads'], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'sonnet', install_source: 'builtin' },
]

const hooks: MarketplaceItem[] = [
  { id: 'hook:pre-deploy-check', type: 'hook', name: 'Pre-Deploy Health Check', description: 'Runs health check before deployments', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['deploy', 'health', 'safety'], triggers: [], provides_tools: [], requires: [], conflicts: [], context_cost: 0, tier: 'flash', install_source: 'builtin', config: { event: 'pre-task', command: 'echo "Pre-deploy check passed"' } },
  { id: 'hook:post-task-log', type: 'hook', name: 'Task Completion Logger', description: 'Logs every AI task completion for audit trail', author: 'Livinity', version: '1.0.0', category: 'Observability', tags: ['logging', 'audit', 'task'], triggers: [], provides_tools: [], requires: [], conflicts: [], context_cost: 0, tier: 'any', install_source: 'builtin', config: { event: 'post-task', command: 'echo "$(date -Iseconds) Task completed" >> /opt/livos/data/task-audit.log' } },
]

const prompts: MarketplaceItem[] = [
  { id: 'prompt:coding-assistant', type: 'prompt', name: 'Coding Assistant', description: 'Expert programmer — clean code, SOLID, TypeScript, tests', author: 'Livinity', version: '1.0.0', category: 'Development', tags: ['coding', 'programming', 'developer'], triggers: [], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'sonnet', install_source: 'builtin', config: { template: 'You are an expert programmer. Clean, well-documented code. SOLID principles. TypeScript by default. Error handling and tests.' } },
  { id: 'prompt:sysadmin', type: 'prompt', name: 'System Administrator', description: 'Linux sysadmin — server management, networking, security', author: 'Livinity', version: '1.0.0', category: 'Infrastructure', tags: ['sysadmin', 'linux', 'server', 'networking'], triggers: [], provides_tools: [], requires: [], conflicts: [], context_cost: 50, tier: 'sonnet', install_source: 'builtin', config: { template: 'Expert Linux sysadmin. Server management, networking, security hardening, automation. Check before destructive changes. Prefer systemd.' } },
]

export const catalog: MarketplaceItem[] = [...mcpServers, ...agents, ...skills, ...hooks, ...prompts]
export const categories = [...new Set(catalog.map(i => i.category))].sort()
export const types = [...new Set(catalog.map(i => i.type))].sort()
