// livos/packages/livinityd/source/modules/local-dns/dnsmasq-config.ts
// Source: 104-PATTERNS.md "dnsmasq-config.ts (service)" — mirrors domain/caddy.ts shape.
//
// Phase 104 plan 104-03 — emits the same /etc/dnsmasq.d/livinity.conf content
// that install.sh's mode-local-lan.sh writes at install time. livinityd can
// regenerate this file when the user changes their TLD or host IP via tRPC.

import {writeFile} from 'node:fs/promises'
import {exec} from 'node:child_process'
import {promisify} from 'node:util'

const execAsync = promisify(exec)

export const DNSMASQ_CONF_PATH = '/etc/dnsmasq.d/livinity.conf'

/**
 * Generate the /etc/dnsmasq.d/livinity.conf content for local-lan mode.
 * Matches the install.sh template byte-for-byte (RESEARCH §Example 1).
 */
export function generateLivinityDnsmasqConfig(tld: string, hostIp: string): string {
	return [
		'# Generated by livinityd local-dns module (Phase 104 plan 104-03)',
		'# Edit /etc/dnsmasq.d/livinity-override.conf for local overrides.',
		`address=/.${tld}/${hostIp}`,
		`local=/${tld}/`,
		'no-resolv',
		'server=1.1.1.1',
		'server=1.0.0.1',
		'bind-dynamic',
		'stop-dns-rebind',
		'',
	].join('\n')
}

/** Atomically write dnsmasq config (caller owns reload). */
export async function writeDnsmasqConfig(content: string): Promise<void> {
	await writeFile(DNSMASQ_CONF_PATH, content, 'utf-8')
}

export async function reloadDnsmasq(): Promise<void> {
	await execAsync('systemctl reload dnsmasq || systemctl restart dnsmasq')
}
