// Phase 163-01 — Surface vault context scaffolder (master plan D-V34-C).
//
// Materialises per-app `CLAUDE.md` context files into the LivOS vault at
// /home/bruce/livinity-vault/surfaces/<kind>/<appId>/CLAUDE.md when an app
// is installed, and renames the surface dir to `.deleted-<unixMs>` (move-
// to-trash, deliberately NOT an unlink) when uninstalled.
//
// Both writeSurfaceContext and removeSurfaceContext are NON-FATAL: all
// recoverable errors are reflected in the discriminated-union result;
// the caller (apps.ts::installForUser, native-installer.ts::install)
// must never have its install path fail because a vault write failed
// (vault may be unmounted, permissions wrong, disk full, etc).
//
// Permission model: 0755 dirs / 0644 files / chown -R bruce:bruce.
// chown is best-effort — its failure is logged but never propagated.
//
// Phase 163-02 (next plan) reads these dirs as `cwd` for surface-prefixed
// sessions (`webapp:` / `native:`). Without 163-01 there is nothing to
// point cwd at.

import {mkdir, writeFile, chmod, stat, rename} from 'node:fs/promises'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import path from 'node:path'

const execFileAsync = promisify(execFile)

const NOOP_LOGGER = {log: () => {}, error: () => {}}
const DEFAULT_VAULT_PATH = '/home/bruce/livinity-vault'
const DEFAULT_OWNER_USER = 'bruce'
const DEFAULT_OWNER_GROUP = 'bruce'

// ─── Public types ────────────────────────────────────────────────────────

export type SurfaceKind = 'webapp' | 'native'

export interface SurfaceMetadata {
	appId: string // e.g. 'suna', 'blender'
	name: string // human-readable display name
	description?: string
	category?: string
	subdomain?: string // webapp only — '<appId>-<username>'
	binaryPath?: string // native only — manifest.launch.binaryPath
	appSpecificHint?: string // optional — appended to "Tools Available"
}

export interface WriteSurfaceContextOptions {
	kind: SurfaceKind
	metadata: SurfaceMetadata
	vaultPath?: string // default '/home/bruce/livinity-vault'
	ownerUser?: string // default 'bruce'
	ownerGroup?: string // default 'bruce'
	logger?: {log: (m: string) => void; error: (m: string, err?: unknown) => void}
}

export type WriteSurfaceContextResult =
	| {status: 'written'; path: string}
	| {status: 'failed-non-fatal'; reason: string}

export interface RemoveSurfaceContextOptions {
	kind: SurfaceKind
	appId: string
	vaultPath?: string // default '/home/bruce/livinity-vault'
	logger?: {log: (m: string) => void; error: (m: string, err?: unknown) => void}
}

export type RemoveSurfaceContextResult =
	| {status: 'renamed'; from: string; to: string}
	| {status: 'absent'}
	| {status: 'failed-non-fatal'; reason: string}

// ─── Template renderers (pure — testable, no I/O) ─────────────────────────
//
// The template literal content begins immediately after the opening
// backtick at column 0 of its content — the rendered output must NOT
// have leading whitespace per line. Do NOT reformat or re-indent these
// strings; the runtime invariants (test 6/7) regex-match against the
// flush-left output.

function renderWebappTemplate(m: SurfaceMetadata): string {
	const generatedAt = new Date().toISOString()
	return `# WebApp Context: ${m.name}

You are operating inside the **${m.name}** WebApp on the user's LivOS desktop.

## App Metadata
- **App ID:** ${m.appId}
- **Subdomain:** ${m.subdomain ?? 'n/a'}
- **Category:** ${m.category ?? 'unspecified'}
- **Description:** ${m.description ?? '(no description provided)'}

## Tools Available
This is a computer-use surface. You have access to:
- \`mcp__luse__*\` (screenshot, click, type, key, application launcher)
- Standard Read/Edit/Bash for file work
- ${m.appSpecificHint ?? '(no app-specific tooling notes)'}

## Cross-Surface Memory
User-level preferences and project context are available via:
- [[user/bruce-profile]]
- [[projects/v34]]
- [[references/mini-pc]]

## Constraints
- Stay in this app's window unless explicitly asked to switch
- Do NOT touch other apps' state
- Respect Phase 160 sandbox path restrictions

<!-- Generated by Phase 163-01 surface-context.ts at ${generatedAt}. Do not hand-edit — regenerated on each install. -->
`
}

function renderNativeTemplate(m: SurfaceMetadata): string {
	const generatedAt = new Date().toISOString()
	return `# NativeApp Context: ${m.name}

You are operating inside the **${m.name}** NativeApp on the user's LivOS desktop.

## App Metadata
- **App ID:** ${m.appId}
- **Binary Path:** ${m.binaryPath ?? 'n/a'}
- **Category:** ${m.category ?? 'unspecified'}
- **Description:** ${m.description ?? '(no description provided)'}

## Tools Available
This is a computer-use surface. You have access to:
- \`mcp__luse__*\` (screenshot, click, type, key, application launcher)
- Standard Read/Edit/Bash for file work
- ${m.appSpecificHint ?? '(no app-specific tooling notes)'}

## Cross-Surface Memory
User-level preferences and project context are available via:
- [[user/bruce-profile]]
- [[projects/v34]]
- [[references/mini-pc]]

## Constraints
- Stay in this app's window unless explicitly asked to switch
- Do NOT touch other apps' state
- Respect Phase 160 sandbox path restrictions

<!-- Generated by Phase 163-01 surface-context.ts at ${generatedAt}. Do not hand-edit — regenerated on each install. -->
`
}

// ─── Public API ──────────────────────────────────────────────────────────

/**
 * Materialise (or overwrite) the per-surface CLAUDE.md for an installed app.
 *
 * Idempotent: re-running with the same args overwrites the same path. The
 * file body itself includes a `Generated by … at <ISO>` footer comment so
 * the mtime advances on every call.
 *
 * Non-fatal: NEVER throws. All errors collapse to
 * `{status: 'failed-non-fatal', reason}` so the caller can keep going.
 */
export async function writeSurfaceContext(
	opts: WriteSurfaceContextOptions,
): Promise<WriteSurfaceContextResult> {
	const logger = opts.logger ?? NOOP_LOGGER
	const vaultPath = opts.vaultPath ?? DEFAULT_VAULT_PATH
	const ownerUser = opts.ownerUser ?? DEFAULT_OWNER_USER
	const ownerGroup = opts.ownerGroup ?? DEFAULT_OWNER_GROUP
	const surfaceDir = path.join(vaultPath, 'surfaces', opts.kind, opts.metadata.appId)
	const claudeMdPath = path.join(surfaceDir, 'CLAUDE.md')
	try {
		await mkdir(surfaceDir, {recursive: true, mode: 0o755})
		const body =
			opts.kind === 'webapp'
				? renderWebappTemplate(opts.metadata)
				: renderNativeTemplate(opts.metadata)
		await writeFile(claudeMdPath, body, {encoding: 'utf8', mode: 0o644})
		// Explicit chmod — writeFile's `mode` option only applies on file
		// creation, not on overwrite. The chmod here guarantees the file
		// is 0644 even on the idempotent re-write path.
		await chmod(claudeMdPath, 0o644)
		// Best-effort chown. The scaffolder runs as livinityd's uid which is
		// either root (Mini PC systemd) or a non-privileged dev user (CI).
		// On a non-root or non-Linux box this will throw; we log + continue.
		try {
			await execFileAsync('chown', ['-R', `${ownerUser}:${ownerGroup}`, surfaceDir])
		} catch (err) {
			logger.error(
				`writeSurfaceContext: chown ${surfaceDir} failed (continuing)`,
				err,
			)
		}
		logger.log(
			`writeSurfaceContext: wrote ${claudeMdPath} (kind=${opts.kind} appId=${opts.metadata.appId})`,
		)
		return {status: 'written', path: claudeMdPath}
	} catch (err) {
		logger.error(
			`writeSurfaceContext: failed for kind=${opts.kind} appId=${opts.metadata.appId}`,
			err,
		)
		return {
			status: 'failed-non-fatal',
			reason: err instanceof Error ? err.message : String(err),
		}
	}
}

/**
 * Move-to-trash the per-surface dir on uninstall.
 *
 * Renames `vault/surfaces/<kind>/<appId>` → `<dir>.deleted-<unixMs>`.
 * This is deliberately a rename (NOT an unlink) so the operator can
 * recover the directory if the uninstall was accidental.
 *
 * Non-fatal: NEVER throws. Missing dir → `{status: 'absent'}`. Any other
 * failure → `{status: 'failed-non-fatal', reason}`.
 */
export async function removeSurfaceContext(
	opts: RemoveSurfaceContextOptions,
): Promise<RemoveSurfaceContextResult> {
	const logger = opts.logger ?? NOOP_LOGGER
	const vaultPath = opts.vaultPath ?? DEFAULT_VAULT_PATH
	const surfaceDir = path.join(vaultPath, 'surfaces', opts.kind, opts.appId)
	try {
		const s = await stat(surfaceDir).catch(() => null)
		if (!s || !s.isDirectory()) {
			logger.log(`removeSurfaceContext: ${surfaceDir} absent, no-op`)
			return {status: 'absent'}
		}
		const trashed = `${surfaceDir}.deleted-${Date.now()}`
		await rename(surfaceDir, trashed)
		logger.log(`removeSurfaceContext: renamed ${surfaceDir} -> ${trashed}`)
		return {status: 'renamed', from: surfaceDir, to: trashed}
	} catch (err) {
		logger.error(
			`removeSurfaceContext: failed for kind=${opts.kind} appId=${opts.appId}`,
			err,
		)
		return {
			status: 'failed-non-fatal',
			reason: err instanceof Error ? err.message : String(err),
		}
	}
}
