version: "3.7"

services:
  tor_proxy:
    container_name: tor_proxy
    image: livos/tor:0.4.7.8
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${LIVINITY_TORRC}:/etc/tor/torrc:ro
      - ${LIVINITY_DATA_DIR}/tor/data:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: $TOR_PROXY_IP
networks:
  default:
    name: livinity_main_network
    ipam:
      driver: default
      config:
        - subnet: "$NETWORK_IP/16"
