#!/usr/bin/env bash
# install-liv-caddy-snippet.sh — Phase 226-04 DEPRECATION STUB
#
# Original purpose (Plan 226-01): copy caddy/conf.d/liv-assistant.caddy under
# /etc/caddy/conf.d/, ensure two `import` lines in /etc/caddy/Caddyfile, run
# a Caddyfile syntax check.
#
# Why deprecated (Plan 226-03 Findings 1+2+3 → Plan 226-04 fix):
#   /etc/caddy/Caddyfile is dynamically generated by livinityd's Caddyfile
#   emitter at livos/packages/livinityd/source/modules/domain/caddy.ts (Phase
#   86 / Phase 218 lineage). The emitter has 3 documented reloadCaddy() call
#   sites + 2 direct writeFile paths. Any in-place edit by THIS script would
#   be wiped on the next regen trigger (app install / share / subdomain
#   change / domain change). Plan 226-04 moves the /liv routing directly into
#   caddy.ts's bruce.livinity.io block emitter via a new LIV_ASSISTANT_HANDLE
#   constant — that emission survives every regen.
#
# This stub stays in the repo so update.sh's Plan 226-02 Step 4.7 invocation
# continues to succeed (exit 0). The stub does no Caddy work — that's now
# livinityd's responsibility. Removing this file outright would break update.sh
# until update.sh's Step 4.7 invocation is also removed (a larger churn).
#
# DO NOT add new behavior to this file. New Caddy routing additions belong in
# livos/packages/livinityd/source/modules/domain/caddy.ts.

set -euo pipefail

readonly TAG="[install-liv-caddy-snippet]"

echo "${TAG} DEPRECATED: /liv routing moved to livinityd caddy.ts emit (Phase 226-04). This script is a no-op."
echo "${TAG} See livos/packages/livinityd/source/modules/domain/caddy.ts LIV_ASSISTANT_HANDLE constant + 3 emit sites (apex, multi-user subdomain, fallback :80)."
echo "${TAG} caddy/conf.d/liv-assistant.caddy in repo is REFERENCE ONLY documentation of the same directive shape."

exit 0
