/**
 * Phase 204-01 — EnvFileWriter unit tests.
 *
 * 1. formatEnvFile() emits sorted KEY=VALUE lines.
 * 2. sync() chmod 0600 + correct body.
 * 3. sync() falls back to secondary path on simulated EACCES.
 * 4. formatEnvFile() is byte-deterministic for the same input.
 */

import {describe, expect, test} from 'vitest'

import {
	EnvFileWriter,
	InvalidKeyFormatError,
	formatEnvFile,
	type EnvFileWriterFs,
} from './env-file-writer.js'

interface InMemoryFile {
	body: string
	mode: number
}

/**
 * In-memory filesystem stub. Tracks every write so the test can assert mode
 * + body. Simulates EACCES by adding a path to the `deny` set.
 */
function makeInMemoryFs(opts: {deny?: Set<string>} = {}): {
	fs: EnvFileWriterFs
	files: Map<string, InMemoryFile>
	dirs: Set<string>
} {
	const files = new Map<string, InMemoryFile>()
	const dirs = new Set<string>()
	const deny = opts.deny ?? new Set<string>()
	const fs: EnvFileWriterFs = {
		writeAtomic(target, body, mode) {
			if (deny.has(target)) {
				const err = new Error(`EACCES: permission denied, open '${target}'`)
				;(err as NodeJS.ErrnoException).code = 'EACCES'
				throw err
			}
			files.set(target, {body, mode})
		},
		mkdirRecursive(dir, _mode) {
			if (deny.has(dir)) {
				const err = new Error(`EACCES: permission denied, mkdir '${dir}'`)
				;(err as NodeJS.ErrnoException).code = 'EACCES'
				throw err
			}
			dirs.add(dir)
		},
		statMode(target) {
			return files.get(target)?.mode ?? null
		},
	}
	return {fs, files, dirs}
}

/**
 * Minimal keyStore stub — only the `getAllForEnvFile` shape the writer touches.
 */
function makeKeyStore(map: Record<string, string>): {getAllForEnvFile: () => Promise<Record<string, string>>} {
	return {
		async getAllForEnvFile() {
			return {...map}
		},
	}
}

describe('formatEnvFile', () => {
	test('1. emits sorted KEY=VALUE lines for each provider', () => {
		const body = formatEnvFile(
			{
				XAI_API_KEY: 'xai-aaaa1234',
				GROQ_API_KEY: 'gsk_bbbb5678',
				ANTHROPIC_API_KEY: 'sk-ant-ccccdddd',
			},
			'2026-05-24T00:00:00.000Z',
		)
		// Banner comments present.
		expect(body).toContain('# Generated by livinityd Phase 204-01')
		expect(body).toContain('# Last sync: 2026-05-24T00:00:00.000Z')
		// Sorted alphabetically — ANTHROPIC < GROQ < XAI.
		const lines = body.split('\n').filter((l) => l && !l.startsWith('#'))
		expect(lines).toEqual([
			'ANTHROPIC_API_KEY=sk-ant-ccccdddd',
			'GROQ_API_KEY=gsk_bbbb5678',
			'XAI_API_KEY=xai-aaaa1234',
		])
	})

	test('4. byte-deterministic for the same input + timestamp', () => {
		const map = {XAI_API_KEY: 'xai-abc12345'}
		const ts = '2026-05-24T00:00:00.000Z'
		const a = formatEnvFile(map, ts)
		const b = formatEnvFile(map, ts)
		expect(a).toBe(b)
	})

	test('rejects malformed values with InvalidKeyFormatError', () => {
		expect(() =>
			formatEnvFile({XAI_API_KEY: 'short'}, '2026-05-24T00:00:00.000Z'),
		).toThrow(InvalidKeyFormatError)
	})
})

describe('EnvFileWriter.sync', () => {
	test('2. writes the primary path with chmod 0600', async () => {
		const {fs, files} = makeInMemoryFs()
		const writer = new EnvFileWriter({
			keyStore: makeKeyStore({XAI_API_KEY: 'xai-validkey1234'}),
			primaryPath: '/etc/default/liv-claw-gateway',
			fallbackPath: '/opt/livos/etc/liv-claw-gateway.env',
			fs,
		})
		const {path: chosen, mode} = await writer.sync()
		expect(chosen).toBe('/etc/default/liv-claw-gateway')
		expect(mode).toBe(0o600)
		const written = files.get(chosen)
		expect(written?.body).toContain('XAI_API_KEY=xai-validkey1234')
		expect(written?.mode).toBe(0o600)
	})

	test('3. falls back to /opt/livos/etc when /etc/default/ denies EACCES', async () => {
		const deny = new Set<string>(['/etc/default/liv-claw-gateway'])
		const {fs, files} = makeInMemoryFs({deny})
		const writer = new EnvFileWriter({
			keyStore: makeKeyStore({GROQ_API_KEY: 'gsk_validkey1234'}),
			primaryPath: '/etc/default/liv-claw-gateway',
			fallbackPath: '/opt/livos/etc/liv-claw-gateway.env',
			fs,
		})
		const {path: chosen, mode} = await writer.sync()
		expect(chosen).toBe('/opt/livos/etc/liv-claw-gateway.env')
		expect(mode).toBe(0o600)
		expect(files.has('/etc/default/liv-claw-gateway')).toBe(false)
		const written = files.get(chosen)
		expect(written?.body).toContain('GROQ_API_KEY=gsk_validkey1234')
	})
})
