/**
 * Phase 204-01 — env-file writer for `liv-claw-gateway`.
 *
 * Emits the LLM provider keys held in Redis (via ProviderKeyStore) to a
 * disk env file that `liv-claw-gateway.service` reads at process boot via
 * `EnvironmentFile=-/etc/default/liv-claw-gateway` (D-204-05).
 *
 * Strategy:
 *   1. Read full env-var map via `keyStore.getAllForEnvFile()`.
 *   2. Build a deterministic text body (sorted by env var name, leading
 *      banner comment with timestamp).
 *   3. Try atomic write (tmp + rename) to the PRIMARY path
 *      `/etc/default/liv-claw-gateway` with chmod 0600.
 *   4. On EACCES / EPERM (livinityd runs as `bruce`; `/etc/default/` is
 *      typically root:root drwxr-xr-x), fall back to the SECONDARY path
 *      `/opt/livos/etc/liv-claw-gateway.env`. The matching systemd unit
 *      should reference BOTH paths via `EnvironmentFile=-` (Plan 204-02
 *      bootstrap step patches the unit).
 *   5. Record the chosen path in Redis (`liv:provider:env-file-path`) so
 *      we don't re-probe `/etc/default/` on every sync after the first
 *      successful write — this also means tests can override the path
 *      sticky-state.
 *
 * Validation (T-204-04): every value MUST match `^[A-Za-z0-9_\-\.]{8,500}$`
 * BEFORE write. Defense-in-depth — the tRPC layer also validates via zod;
 * this is the last line before disk so a malformed value can't tip the
 * systemd unit into a restart loop.
 *
 * INV-204-05 — file mode is ALWAYS 0o600 (root or bruce-only readable).
 */

import {
	chmodSync,
	mkdirSync,
	renameSync,
	statSync,
	writeFileSync,
} from 'node:fs'
import path from 'node:path'

import type {ProviderKeyStore} from './key-store.js'

// ── Paths ────────────────────────────────────────────────────────────────

/**
 * Mini PC primary path. `liv-claw-gateway.service` references this via
 * `EnvironmentFile=-/etc/default/liv-claw-gateway` (already in the unit
 * shipped by Phase 203-03). The `-` prefix makes it optional.
 */
export const ENV_FILE_PRIMARY = '/etc/default/liv-claw-gateway'

/**
 * livinityd-owned fallback. Used when the writer cannot write to the
 * primary path (typical case: livinityd runs as `bruce`, `/etc/default/`
 * requires root). Plan 204-02 patches `liv-claw-gateway.service` with a
 * second `EnvironmentFile=-` directive pointing here.
 */
export const ENV_FILE_FALLBACK = '/opt/livos/etc/liv-claw-gateway.env'

/** Redis key for sticky path choice (avoids re-probing /etc/default/ on every sync). */
export const ENV_FILE_PATH_REDIS_KEY = 'liv:provider:env-file-path'

// ── Validation ───────────────────────────────────────────────────────────

/**
 * Strict key shape — must match what zod accepts at the tRPC layer
 * (T-204-04 defense-in-depth). Allows alphanumeric + underscore + dash +
 * dot (covers `sk-...`, `xai-...`, `gsk_...`, dotted ollama base URLs).
 */
export const KEY_SHAPE_REGEX = /^[A-Za-z0-9_\-.]{8,500}$/

export class InvalidKeyFormatError extends Error {
	constructor(envVar: string) {
		super(`INVALID_KEY_FORMAT: value for ${envVar} does not match ^[A-Za-z0-9_\\-.]{8,500}$`)
		this.name = 'InvalidKeyFormatError'
	}
}

// ── Pure helpers (exported for tests) ────────────────────────────────────

/**
 * Build the deterministic env-file body. Lines are sorted by env-var name
 * so two successive syncs over the same map produce byte-identical output
 * (test case env-file-writer.test.ts #4).
 *
 * Trailing newline included — systemd's EnvironmentFile parser is line-
 * delimited and bare last-lines without a newline have bitten us before.
 */
export function formatEnvFile(
	map: Record<string, string>,
	timestamp: string,
): string {
	const lines: string[] = [
		'# Generated by livinityd Phase 204-01 — do not edit by hand.',
		`# Last sync: ${timestamp}`,
		'#',
		'# To set or remove keys, open https://bruce.livinity.io/liv-ai-app/settings',
		'# and use the Providers tab. Direct edits will be overwritten on the next save.',
		'',
	]
	const sorted = Object.entries(map).sort(([a], [b]) => a.localeCompare(b))
	for (const [envVar, value] of sorted) {
		if (!KEY_SHAPE_REGEX.test(value)) {
			throw new InvalidKeyFormatError(envVar)
		}
		lines.push(`${envVar}=${value}`)
	}
	return lines.join('\n') + '\n'
}

/**
 * Detect EACCES/EPERM/ENOENT-on-parent. Wrapped in a helper so tests can
 * inject the synthetic failure cleanly.
 */
function isPermissionError(err: unknown): boolean {
	if (typeof err !== 'object' || err === null) return false
	const code = (err as {code?: string}).code
	return code === 'EACCES' || code === 'EPERM' || code === 'ENOENT'
}

// ── Filesystem hook (test seam) ──────────────────────────────────────────

/**
 * Filesystem operations split into an injectable interface so tests can
 * simulate EACCES on the primary path without `chmod`-fighting Windows.
 */
export interface EnvFileWriterFs {
	writeAtomic(target: string, body: string, mode: number): void
	mkdirRecursive(dir: string, mode: number): void
	statMode(target: string): number | null
}

export const defaultFs: EnvFileWriterFs = {
	writeAtomic(target, body, mode) {
		const tmp = `${target}.tmp-${process.pid}-${Date.now()}`
		writeFileSync(tmp, body, {mode})
		try {
			chmodSync(tmp, mode)
		} catch {
			// chmod failure on tmp is non-fatal — rename will keep the mode
			// from writeFileSync's `mode` option on POSIX. On Windows, mode
			// is largely ignored anyway.
		}
		renameSync(tmp, target)
	},
	mkdirRecursive(dir, mode) {
		mkdirSync(dir, {recursive: true, mode})
	},
	statMode(target) {
		try {
			return statSync(target).mode & 0o777
		} catch {
			return null
		}
	},
}

// ── Redis surface (just two methods we use) ──────────────────────────────

export interface EnvFileWriterRedis {
	get(key: string): Promise<string | null>
	set(key: string, value: string): Promise<unknown>
}

// ── Class ────────────────────────────────────────────────────────────────

export interface EnvFileWriterLogger {
	info(msg: string): void
	warn(msg: string, error?: unknown): void
}

export interface EnvFileWriterOptions {
	keyStore: Pick<ProviderKeyStore, 'getAllForEnvFile'>
	redis?: EnvFileWriterRedis
	logger?: EnvFileWriterLogger
	/** Override primary path (tests). */
	primaryPath?: string
	/** Override fallback path (tests). */
	fallbackPath?: string
	/** Override filesystem ops (tests). */
	fs?: EnvFileWriterFs
}

/**
 * `liv-claw-gateway` env-file regenerator. Used by the provider-config
 * tRPC layer on every set/delete to keep disk in sync with Redis.
 */
export class EnvFileWriter {
	private readonly keyStore: Pick<ProviderKeyStore, 'getAllForEnvFile'>
	private readonly redis: EnvFileWriterRedis | undefined
	private readonly logger: EnvFileWriterLogger
	private readonly primaryPath: string
	private readonly fallbackPath: string
	private readonly fs: EnvFileWriterFs

	/** Sticky chosen path (set after the first successful sync). */
	private cachedPath: string | null = null

	constructor(opts: EnvFileWriterOptions) {
		this.keyStore = opts.keyStore
		this.redis = opts.redis
		this.logger = opts.logger ?? {
			info: () => undefined,
			warn: () => undefined,
		}
		this.primaryPath = opts.primaryPath ?? ENV_FILE_PRIMARY
		this.fallbackPath = opts.fallbackPath ?? ENV_FILE_FALLBACK
		this.fs = opts.fs ?? defaultFs
	}

	/**
	 * Regenerate the env file from the current Redis state.
	 *
	 * Returns the chosen path + mode for observability (the router surfaces
	 * the path in its response so the UI's restart banner can point to the
	 * right file).
	 */
	async sync(): Promise<{path: string; mode: number}> {
		const envMap = await this.keyStore.getAllForEnvFile()

		// Phase 203 Hot-fix F5 — propagate LIV_API_KEY into the gateway env
		// file so the openclaw plugin's livinityd HTTP client (app-store.ts)
		// can authenticate via the `X-Api-Key` service-token path. Without
		// this, `openclawos.apps.list` returns 401 and the desktop-integration
		// flow (Plan 203-10) cannot fetch the OpenUI apps list. Only injected
		// when the env var is present AND matches the writer's key-shape
		// regex (defense-in-depth — keeps the gateway out of a restart loop
		// if /opt/livos/.env is malformed).
		const livApiKey = process.env['LIV_API_KEY']
		if (typeof livApiKey === 'string' && KEY_SHAPE_REGEX.test(livApiKey)) {
			envMap['LIV_API_KEY'] = livApiKey
		}

		const body = formatEnvFile(envMap, new Date().toISOString())

		// If we've previously chosen a path successfully, stay sticky. Avoid
		// re-probing /etc/default/ every save — the typical case is that the
		// first sync after upgrade picks the fallback path, and we want
		// subsequent syncs to be idempotent on that choice.
		if (this.cachedPath === null && this.redis) {
			try {
				this.cachedPath = await this.redis.get(ENV_FILE_PATH_REDIS_KEY)
			} catch (err) {
				this.logger.warn(
					'[env-file-writer] failed to read sticky path from Redis (non-fatal)',
					err,
				)
			}
		}

		const candidates = this.cachedPath
			? [this.cachedPath, this.primaryPath, this.fallbackPath].filter(
					(p, i, arr) => arr.indexOf(p) === i,
				)
			: [this.primaryPath, this.fallbackPath]

		let lastErr: unknown = null
		for (const target of candidates) {
			try {
				const dir = path.dirname(target)
				// Ensure parent exists for the fallback path (tests + first deploy).
				// For /etc/default/ this is a no-op on Mini PC.
				try {
					this.fs.mkdirRecursive(dir, 0o700)
				} catch (mkdirErr) {
					if (!isPermissionError(mkdirErr)) throw mkdirErr
					// Permission error creating parent → this path won't work.
					// Continue to the next candidate.
					throw mkdirErr
				}
				this.fs.writeAtomic(target, body, 0o600)
				const mode = this.fs.statMode(target) ?? 0o600
				this.cachedPath = target
				if (this.redis) {
					try {
						await this.redis.set(ENV_FILE_PATH_REDIS_KEY, target)
					} catch (redisErr) {
						this.logger.warn(
							'[env-file-writer] failed to persist sticky path to Redis (non-fatal)',
							redisErr,
						)
					}
				}
				this.logger.info(
					`[env-file-writer] wrote ${target} (${Object.keys(envMap).length} keys, mode=${mode.toString(8)})`,
				)
				return {path: target, mode}
			} catch (err) {
				lastErr = err
				if (!isPermissionError(err)) {
					// Non-permission error → rethrow (e.g. ENOSPC, EROFS — caller surfaces).
					throw err
				}
				this.logger.warn(
					`[env-file-writer] permission denied writing ${target} — trying next candidate`,
				)
				continue
			}
		}

		// Exhausted both paths.
		throw lastErr ?? new Error('env-file-writer: no writable path candidate')
	}

	/**
	 * Test seam — synchronous accessor for the sticky path.
	 */
	getCachedPath(): string | null {
		return this.cachedPath
	}
}
